[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-musl-gcc"
strip = { path = "aarch64-linux-musl-strip" }

[target.armv7-unknown-linux-musl]
linker = "arm-linux-gnueabihf-gcc"
strip = { path = "arm-linux-gnueabihf-strip" }
