[target.x86_64-unknown-linux-musl]
linker = "x86_64-linux-musl-gcc"
strip = "x86_64-linux-musl-strip"
[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-musl-gcc"
strip = "aarch64-linux-musl-strip"
